trigger:
  - master

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/Be.Stateless.Build.Agent.Yaml.Pipeline.Templates
      ref: refs/heads/use-vstest
      endpoint: github.com_icraftsoftware

extends:
  template: Pipelines/net/continuous-integration.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Be.Stateless.BizTalk.ServiceModel.sln"
    Major: 2
    Minor: 0
    TestEngine: vstest
